config/routes.rb
Rails.application.routes.draw do
  devise_for :testers
  resources :executions
  resources :test_runs
  resources :test_plans
  resources :features do
    resources :scenarios
  end
  root 'features#index'
end

app/models/execution.rb
class Execution < ActiveRecord::Base
  belongs_to :test_run
  belongs_to :step
  as_enum :result, fail: 0, pass: 1, prefix: true
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  has_many :test_runs
  has_many :test_plans, through: :test_runs
  has_many :scenarios, dependent: :destroy
  accepts_nested_attributes_for :scenarios,
                                reject_if: :all_blank,
                                allow_destroy: true
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :feature
  has_many :test_runs
  has_many :test_plans, through: :test_runs
  has_many :steps, dependent: :destroy
  accepts_nested_attributes_for :steps,
                                reject_if: :all_blank,
                                allow_destroy: true
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :scenario
  has_many :executions
end

app/models/test_plan.rb
class TestPlan < ActiveRecord::Base
  has_many :test_runs
  accepts_nested_attributes_for :test_runs
  has_many :scenarios, through: :test_runs
  has_many :testers, through: :test_runs
end

app/models/test_run.rb
class TestRun < ActiveRecord::Base
  belongs_to :tester
  belongs_to :test_plan
  belongs_to :feature
  belongs_to :scenario
  has_many :executions, dependent: :destroy
end

app/models/tester.rb
class Tester < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :test_runs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
    @features = Feature.all
  end

  def new
    @feature = Feature.new.tap {|f| f.scenarios.new.tap {|s| s.steps.new}}
  end

  def create
    Feature.new(feature_params).save
    flash[:success] = 'you did it!'
    redirect_to features_path
  end

  def edit
    @feature = Feature.find(params[:id])
  end

  def update
    @feature = Feature.find(params[:id])
    if @feature.update_attributes(feature_params)
      flash[:success] = 'You updated it!'
      redirect_to features_path
    else
      flash[:error] = 'Uh oh!'
      render :edit
    end
  end

  private

  def feature_params
    params.require(:feature).permit(
      :title,
      scenarios_attributes: [
        :id, :_destroy, :title,
        steps_attributes: [
          :id, :_destroy, :title
        ]
      ]
    )
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  helper_method :feature, :scenario

  def edit;end

  def update
    if scenario.update(scenario_params)
      flash[:success] = 'You updated the scenario!'
      redirect_to features_path
    else
      flash[:error] = 'Uh oh!'
      render :edit
    end
  end

  def destroy
    scenario.destroy
    flash[:success] = 'Scenario destroyed'
    redirect_to features_path
  end

  private

  def scenario_params
    params.require(:scenario).permit(
      :id, :_destroy, :title, steps_attributes: [ :id, :_destroy, :title ]
    )
  end

  def scenario
    @scenario ||= feature.scenarios.find(params[:id])
  end

  def feature
    @feature ||= Feature.find(params[:feature_id])
  end
end

app/controllers/test_plans_controller.rb
class TestPlansController < ApplicationController
  def new
    @test_plan = TestPlan.new.tap do |test_plan|
      test_plan.test_runs.new
    end
  end

  def create
    binding.pry
    params
  end

  private

  def testers
    @testers ||= Tester.where(id: params[:test_plan][:tester_ids])
  end

  def build_test_runs
    testers.each do |tester|
      test_plan.test_runs.create(
        test_plan_params.merge(tester_id: tester.id)
      )
    end
  end

  def test_runs_params
    params[:test_plan][:test_runs_attributes]
  end

  def test_plan
    @test_plan ||= TestPlan.find(params[:id]) || TestPlan.create
  end
end

app/controllers/test_runs_controller.rb
class TestRunsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/features/_feature_form.html.erb
<%= f.input :title %>
<div class='row'>
  <div id='scenarios' class='col-md-12'>
    <%= f.simple_fields_for :scenarios do |scenario| %>
      <%= render partial: 'scenarios/scenario_fields', locals: { f: scenario, nested: true } %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add scenario', f, :scenarios, partial: 'scenarios/scenario_fields', class: 'btn btn-default', render_options: { locals: { nested: true } } %>
    </div>
  </div>
</div>
<hr>
<%= f.button :submit, class: 'btn btn-primary' %>

app/views/features/_scenario_fields.html.erb
<div class='well'>
  <%= f.input :title, label: 'Scenario' %>
  <div class='row'>
    <div id='steps' class='col-md-11 col-md-offset-1'>
      <%= f.simple_fields_for :steps do |step| %>
        <%= render partial: 'features/step_fields', locals: { f: step } %>
      <% end %>
      <div class='links'>
        <%= link_to_add_association 'add step', f, :steps %>
      </div>
    </div>
  </div>
</div>

app/views/features/edit.html.erb
<h1>Edit Feature</h1>
<div class='row'>
  <div class='col-md-12'>
    <%= simple_form_for(@feature, html: { class: 'form-horizontal' }) do |f| %>
      <%= render partial: 'feature_form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/features/index.html.erb
<h1>Features index</h1>
<div class="row">
  <div class="col-sm-offset-6 col-sm-6">
    <%= link_to 'Register', new_tester_registration_path, class: 'btn btn-default' %>
    <%= link_to 'Sign in', new_tester_session_path, class: 'btn btn-default' %>
  </div>
</div>
<ul>
  <% @features.each do |feature| %>
    <li><%= link_to feature.title, edit_feature_path(feature) %></li>
    <% feature.scenarios.each do |scenario| %>
      <ul>
        <li>
          <%= link_to scenario.title, edit_feature_scenario_path(feature, scenario) %>
        </li>
        <ul>
          <% scenario.steps.each do |step| %>
            <li><%= step.title %></li>
          <% end %>
        </ul>
      </ul>
    <% end %>
  <% end %>
</ul>
<hr>

<div class="row">
  <div class="col-sm-6">
    <%= link_to 'Create new feature', new_feature_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Create new test plan', new_test_plan_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/features/new.html.erb
<h1>New Feature</h1>
<div class='row'>
  <div class='col-md-12'>
    <%= simple_form_for(@feature, html: { class: 'form-horizontal' }) do |f| %>
      <%= f.input :title %>
      <div class='row'>
        <div id='scenarios' class='col-md-12'>
          <%= f.simple_fields_for :scenarios do |scenario| %>
            <%= render partial: 'features/scenario_fields', locals: { f: scenario } %>
          <% end %>
          <div class='links'>
            <%= link_to_add_association 'add scenario', f, :scenarios %>
          </div>
        </div>
      </div>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manuel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render partial: 'layouts/flashes', flash: flash %>
  <%= yield %>
</div>

</body>
</html>

app/views/scenarios/_field_set_links.html.erb
<%= link_to_add_association 'add step', f, :steps, partial: 'steps/step_fields', class: 'btn btn-default' %>
<%= link_to_remove_association('delete this scenario', f, class: 'btn btn-danger', 'data-confirm' => 'Are you sure you want to destroy this scenario?') %>

app/views/scenarios/_form_links.html.erb
<%= link_to_add_association 'add step', f, :steps, partial: 'steps/step_fields', class: 'btn btn-default' %>
<%= link_to 'delete this scenario', feature_scenario_path(feature, scenario), method: :delete, class: 'btn btn-danger', 'data-confirm' => 'Are you sure you want to destroy this scenario?' %>

app/views/scenarios/_scenario_fields.html.erb
<div class='well nested-fields'>
  <%= f.input :title, label: 'Scenario' %>
  <div class='row'>
    <div id='steps' class='col-md-11 col-md-offset-1'>
      <%= f.simple_fields_for :steps do |step| %>
        <%= render partial: 'steps/step_fields', locals: { f: step } %>
      <% end %>
      <div class='links'>
        <%= render partial: (nested ? 'scenarios/field_set_links' : 'scenarios/form_links'), locals: { f: f } %>
      </div>
    </div>
  </div>
</div>

app/views/scenarios/edit.html.erb
<h1>Edit Scenario</h1>
<div class='row'>
  <div class='col-md-12'>
    <%= simple_form_for([feature, scenario], html: { class: 'form-horizontal' }) do |f| %>
      <%= render partial: 'scenarios/scenario_fields', locals: { f: f, nested: false } %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/steps/_step_fields.html.erb
<div class='nested-fields'>
  <%= f.input :title, label: 'Step' %>
</div>

app/views/test_plans/_test_run_fields.html.erb
<div class='col-md-3 nested-fields'>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= test_run.input :scenario, collection: Scenario.all, multiple: true %>
      <%= link_to_remove_association('delete this scenario', test_run) %>
    </div>
  </div>
</div>

app/views/test_plans/new.html.erb
<h1>Create new Test Plan</h1>
<%= simple_form_for @test_plan do |f| %>
  <h4>Assign Testers</h4>
  <%= f.association :testers, label_method: :email, as: :check_boxes %>
  <h4>Add Test Runs</h4>
  <%= f.simple_fields_for :test_runs do |test_run| %>
    <div id='test_runs' class="row">
      <%= render partial: "test_plans/test_run_fields", locals: { test_run: test_run, f: f  } %>
      <div class='links'>
        <%= link_to_add_association 'add test run', f, :test_runs, partial: 'test_plans/test_run_fields', render_options: { locals: { test_run: test_run, f: f  } }, class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>